#! /bin/bash

# This variable marks path var as set
INVOCATION_ORDER+=('pathsrc')


export INVOCATION_ORDER

export MYPATHSET=1

# PATH RELATED COMMANDS

export PATH="/Users/tom/Library/TeX/LocalTeX/texbin:$PATH" # Add texbin for local tex prefpane

export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.4/bin

export PATH="/usr/local/share/python:$PATH" # Add RVM to PATH for scripting

# Keep this near the end of .profile. It sets path for gui apps in "os x"

launchctl setenv PATH $PATH

export PATH="$PATH:/usr/local/share/python" # Add RVM to PATH for scripting

## Remove duplicated paths
PATH="$(echo $PATH | perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, scalar <>))')"

export PATH
## export to system wide configuration
launchctl setenv PATH $PATH

# additional global environment variables


# Specify defaults for homebrew cask in this environment variable
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"




# Other Environment var customization:

export PYTHONPATH=/usr/local/lib/python2.7/site-packages

export PYTHONSTARTUP=~/.pythonrc


export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh

source /usr/local/bin/virtualenvwrapper_lazy.sh

# Some access stuff for aws -- do not put actual file  in .dotfiles repo!
source ~/.aws/awsrc.sh